services:

  sylius_apisearch.command.populate:
    class: Apisearch\SyliusApisearchPlugin\Command\PopulateCommand
    arguments:
      - "@sylius_apisearch.indexing.resetting"
      - "@sylius_apisearch.indexing.populate"
      - "@sylius.repository.product"
    tags:
      - { name: console.command }

  sylius_apisearch.command.reset:
    class: Apisearch\SyliusApisearchPlugin\Command\ResetCommand
    arguments:
      - "@sylius_apisearch.indexing.resetting"
    tags:
      - { name: console.command }
