services:

  sylius_apisearch.controller.taxon:
      class: Apisearch\SyliusApisearchPlugin\Controller\TaxonController
      public: true
      arguments:
       - "@sylius_apisearch.configuration"
       - "@sylius_apisearch.context.taxon"
       - "@sylius_apisearch.search"
       - "@templating"
