services:

  sylius_apisearch.controller.taxon_static:
      class: Apisearch\SyliusApisearchPlugin\Controller\TaxonStaticController
      public: true
      arguments:
       - "@sylius_apisearch.configuration"
       - "@sylius_apisearch.context.taxon"
       - "@sylius_apisearch.search"
       - "@templating"