services:

  sylius_apisearch.listener.product:
    class: Apisearch\SyliusApisearchPlugin\EventListener\ProductListener
    arguments:
      - "@sylius_apisearch.indexing.populate"
    tags:
      -  { name: kernel.event_listener, event: sylius.product.post_create, method: onCreate }
      -  { name: kernel.event_listener, event: sylius.product.post_update, method: onUpdate }
      -  { name: kernel.event_listener, event: sylius.product.post_delete, method: onDelete }
