services:

  sylius_apisearch.populate.resetting:
      class: Apisearch\SyliusApisearchPlugin\Populate\Resetting
      arguments:
        - "@sylius_apisearch.configuration"
        - "@apisearch.repository_bucket"

  sylius_apisearch.populate.populate:
      class: Apisearch\SyliusApisearchPlugin\Populate\Populate
      arguments:
        - "@sylius.repository.product"
        - "@sylius_apisearch.repository"
        - "@sylius_apisearch.transformer.product"