services:

  sylius_apisearch.search.search:
      class: Apisearch\SyliusApisearchPlugin\Search\Search
      arguments:
        - "@sylius_apisearch.repository"
        - "@sylius_apisearch.configuration"
        - "@sylius_apisearch.url.url_builder"
        - "@sylius.context.locale"