sylius_shop_product_index:
    path: /taxons/{slug}
    defaults:
        _controller: sylius_apisearch.controller.taxon
        template: "%sylius_apisearch.config.template%"
    requirements:
        slug: .+