sylius_shop_product_index:
    path: /{_locale}/taxons/{slug}
    defaults:
        _controller: sylius_apisearch.controller.taxon
        template: "%sylius_apisearch.config.template%"
    requirements:
        slug: .+
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
